### PR TITLE
A few new features and improvements to inspect4py

### PR DESCRIPTION
**Pull request by zl81**
In this PR a few new features are added, including: 
- A new input parameter `-sc —-source_code` to generate source code of each ast node
- A new input parameter `-ast —abstract_syntax_tree` to generate ast for each function in json format
- A new input parameter `-ld --license_detection` to detect the most likely license of the target repository
- Extracts type annotations when inspecting functions or methods

There are also some improvements to `inspect4py`, including:
- Changing the call list structure so that calls within functions, body and classes are in separate fields
- Use recursive approach to extract ast nodes, modified methods for inspecting class/function definitions and body calls, so that they can detect calls under clauses like `while`, `if`, `for`, etc.

### CODE REVIEW

**Comment by dgarijo** [comment]
@zl81,
thanks, this looks like great progress for inspect4py.
I need a few days for reviewing the PR. I will produce a review then

**Comment by zl81** [comment]
Thank you, please take your time!

**Comment by rosafilgueira** [comment]
Many thanks @zl81 !

**Review by dgarijo — APPROVED** [review]
looks ok to me. I have to pass the tests locally (I have not set up the actions yet)

**Comment by dgarijo** [comment]
Next time @zl81 please push your changes to the `dev` branch. Thanks!

**Comment by zl81** [comment]
> looks ok to me. I have to pass the tests locally (I have not set up the actions yet)

I have left one test unpassed intentionally, this unpassed test shows an open issue of our current implementation treating class instantialization calls the same as regular function calls, right now we don't have a good way to distinguish between the two.

**Comment by dgarijo** [comment]
Ok. Can you please open an issue? It's easier to track open problems this way.

**Comment by zl81** [comment]
> Ok. Can you please open an issue? It's easier to track open problems this way.

Sure, I will open it tomorrow as it's late in my current time zone.

**Comment by dgarijo** [comment]
Thanks! No rush

**Pull request merged**
